### PR TITLE
Please incorporate the new question

### PR DESCRIPTION
**Pull request by bwentwor**
I added the new "How can I access infrastructure services in my account?" section. This new question needs to be accessible by the chant assistant as well.

### CODE REVIEW

**Comment by bwentwor** [comment]
Typo...Chat assistant. :-)

**Comment by mekaufman** [comment]
Moving this to the correct FAQ page. This isn't specific to IAM/access related issue.

**Comment by ClaireTurner** [comment]
@mekaufman Which IBM doc was this moved to please? I was just checking the FAQ was incorporated. Thanks Claire

**Comment by mekaufman** [comment]
@ClaireTurner https://cloud.ibm.com/docs/account?topic=account-accessing#troubleshoot-infrastructure-access

**Comment by ClaireTurner** [comment]
Thank you very much @mekaufman

**Pull request closed without merging**
